objects:
  blue_cube:
    shape: box
    dimensions: [0.05, 0.05, 0.05]
    position: [0.5, 0.0, 0.3]
    color: [0.0, 0.0, 1.0, 1.0]

  red_cube:
    shape: box
    dimensions: [0.05, 0.05, 0.05]
    position: [0.0, 0.5, 0.3]
    color: [1.0, 0.0, 0.0, 1.0]
